modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="mining_enchant" #mandatory
version="1.1.0" #mandatory
displayName="dododo MOD" #mandatory
authors="${mod_authors}" #optional
description=''''''
[[dependencies.mining_enchant]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mining_enchant]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.mining_enchant]]
modId="terrablender"
mandatory=true
versionRange="${terrablender_version_range}"
ordering="NONE"
side="BOTH"

